In [ ]:
# ВАРІАНТ 6 

In [ ]:
 # Завдання 1. Створіть одновимірний масив (вектор) з перших 10-ти додатних парних чисел та виведіть його значення

In [1]:
import numpy as np

In [2]:
a = np.array([2,4,6,8,10,12,14,16,18,20], dtype = float)

In [3]:
print(a)

[ 2.  4.  6.  8. 10. 12. 14. 16. 18. 20.]


In [ ]:
# Завдання 2 Створіть двовимірний масив (матрицю) розміром 3x3, заповніть його сумою кожного числа та його попереднього, починаючи з 1, та виведіть його значення.

In [16]:
matrix2 = np.zeros((3,3), dtype = int )
matrix2[0,0] = 1
cv = 1
temp = 0
for i in range(3):
    for j in range(3):        
        matrix2[i,j] = cv + temp
        cv += 1
        temp = matrix2[i,j]
print(matrix2)

[[ 1  3  6]
 [10 15 21]
 [28 36 45]]


In [ ]:
# Завдання 3 Створіть масив розміром 9x9, заповніть його випадковими цілими числами в діапазоні від 1 до 1000 та виведіть його значення.

In [20]:
matrix3 = np.zeros((9,9), dtype = int )
for i in range(9):
    for j in range(9):        
        matrix3[i,j] = np.random.randint(1, 1001)
print(matrix3)

[[ 75 625 768 391 708 176  71 513  99]
 [104 625 885 162 863 234 933  19 488]
 [607 417 728 584 642 896 836 991 665]
 [492 524 366  22 897 913 755 805 841]
 [622 836 589 409 386 793 504 151 103]
 [334 350 721 190 440 725 402  46 126]
 [293 778 283 124 258 844 405 220 184]
 [243 645 547 587 192 400 173 488 514]
 [921  86 929 289 201 721 836 857 863]]


In [30]:
# Завдання 4 Створіть масив розміром 5x5, заповніть його випадковими дійсними числами в діапазоні від 
# 0 до 1 та знайдіть вектор-стовпчик, що містить суму елементів кожного рядка матриці.
matrix4 = np.zeros((5,5), dtype = int )
for i in range(5):
    for j in range(5):        
        matrix4[i,j] = np.random.randint(0,2)
print(matrix4)
print()
mas4 = np.zeros(5, dtype = int )
for i in range(5):
    for j in range(5):        
        if matrix4[i,j] == 1 :
            mas4[i] += 1
print(mas4)

[[0 1 1 0 1]
 [0 0 1 0 1]
 [0 1 0 1 1]
 [1 0 0 0 0]
 [0 1 1 0 0]]

[3 2 3 1 2]


In [35]:
# Завдання 5 Створіть два одновимірних масиви розміром 5, заповніть їх випадковими 
# дійсними числами від 0 до 1 та виконайте на них поелементні операції додавання, віднімання та множення.
mas51 = np.zeros((5), dtype = int )
for i in range(5):      
        mas51[i] = np.random.randint(0,2)
mas52 = np.zeros((5), dtype = int )
for i in range(5):      
        mas52[i] = np.random.randint(0,2)
print(mas51)
print(mas52)
print()
print(mas51 + mas52)
print(mas51 - mas52)
print(mas51 * mas52)


[0 1 1 1 1]
[0 0 1 0 0]

[0 1 2 1 1]
[0 1 0 1 1]
[0 0 1 0 0]


In [39]:
# Завдання 6 Створіть два вектори розміром 6, заповніть їх довільними 
# дійсними числами та знайдіть їх скалярний добуток.
mas61 = np.zeros((6), dtype = int )
for i in range(6):      
        mas61[i] = np.random.randint(0,10)
mas62 = np.zeros((6), dtype = int )
for i in range(6):      
        mas62[i] = np.random.randint(0,10)
print(mas61)
print(mas62)
print()
scalar_product = np.dot(mas61, mas62)
print(scalar_product)

[6 2 0 2 9 5]
[6 3 5 7 6 7]

145


In [47]:
# Завдання 7 Створіть дві матриці розміром 2x3 та 3x4, заповніть їх випадковими
# цілими числами в діапазоні від 1 до 15 та перемножте їх між собою.
mas71 = np.zeros((2,3), dtype = int )
for i in range(2):
    for j in range(3):        
        mas71[i,j] = np.random.randint(0,15)
mas72 = np.zeros((3,4), dtype = int )
for i in range(3):
    for j in range(4):        
        mas72[i,j] = np.random.randint(0,15)
print(mas71)
print()
print(mas72)
print()
print(np.dot(mas71, mas72))



[[14 10  3]
 [12 12  8]]

[[ 2 13  3 12]
 [ 5  4  4  4]
 [11  5  6  2]]

[[111 237 100 214]
 [172 244 132 208]]


In [49]:
# Завдання 8 Створіть матрицю розміром 3x3, заповніть її випадковими цілими 
# числами в діапазоні від 1 до 8 та знайдіть її обернену матрицю.
mas81 = np.zeros((3,3), dtype = int )
for i in range(3):
    for j in range(3):        
        mas81[i,j] = np.random.randint(0,8)
print(mas81)
print()
mas81_inv = np.linalg.inv(mas81)
print(mas81_inv)


[[5 1 3]
 [7 6 6]
 [5 1 3]]

[[-2.34970415e+15 -3.04347826e-01  2.34970415e+15]
 [-1.76227812e+15  2.17391304e-02  1.76227812e+15]
 [ 4.50359963e+15  5.00000000e-01 -4.50359963e+15]]


In [51]:
# Завдання 9. Створіть матрицю розміром 4x4, заповніть її випадковими
# дійсними числами в діапазоні від 0 до 1 та транспонуйте її.
mas91 = np.zeros((4,4), dtype = int )
for i in range(4):
    for j in range(4):        
        mas91[i,j] = np.random.randint(0,2)
print(mas91)
print()
mas91t = mas91.T
print(mas91t)

[[0 1 1 0]
 [1 0 0 0]
 [1 0 0 1]
 [1 0 0 0]]

[[0 1 1 1]
 [1 0 0 0]
 [1 0 0 0]
 [0 0 1 0]]


In [63]:
# Завдання 10 Створіть матрицю розміром 3x4 та вектор розміром 4, заповніть матрицю випадковими дійсними числами від 0 до 1, 
# а вектор - випадковими дійсними числами від 0 до 1, і знайдіть елементи отриманого вектору, які більше середнього значення вектору.
mas101 = np.zeros((3,4), dtype = float )
mid = 0
mid2 = 0
for i in range(3):
    for j in range(4):        
        mas101[i,j] = np.random.uniform(0,1)
        mid2 += mas101[i,j]
mid = mid2/12
mas102 = np.zeros((4), dtype = float )
mas103 = np.zeros((4), dtype = float )
for i in range(4):    
    mas102[i] = np.random.uniform(0,1)
    if mas102[i] > mid:
        mas103[i] = mas102[i]

print(mas101)
print("Середнє значення =  " + str(mid))
print()
print(mas102)
print("Елементи вектора, які більше середнього значення: ")
for i in range(4):    
    if mas103[i] > 0:
        print(mas103[i])

[[0.45179054 0.35595829 0.48284148 0.00840943]
 [0.87270996 0.98887029 0.08353932 0.69327382]
 [0.02437697 0.9650311  0.98600641 0.21106933]]
Середнє значення =  0.5103230783743823

[0.89361298 0.84136718 0.07646366 0.08744757]
Елементи вектора, які більше середнього значення: 
0.8936129784136224
0.8413671849026194


In [64]:
# Завдання 11 Створіть матрицю розміром 2x3 та вектор розміром 3, заповніть матрицю випадковими цілими числами в діапазоні
# від 1 до 10, а вектор - випадковими дійсними числами від 0 до 1, і знайдіть суму елементів вектору, які більше середнього значення вектору.

mas111 = np.zeros((2,3), dtype = float )
mid = 0
mid2 = 0
for i in range(2):
    for j in range(3):        
        mas111[i,j] = np.random.uniform(0,10)
        mid2 += mas111[i,j]
mid = mid2/12
mas112 = np.zeros((4), dtype = float )
mas113 = np.zeros((4), dtype = float )
for i in range(3):    
    mas112[i] = np.random.uniform(0,1)
    if mas112[i] > mid:
        mas113[i] = mas112[i]

print(mas111)
print("Середнє значення =  " + str(mid))
print()
print(mas112)
sum = 0
print("Сума Елементів вектора, які більше середнього значення: ")
for i in range(4):    
    if mas113[i] > 0:
        sum += mas113[i]
print(sum)

[[6.66805788 8.55713394 8.41579011]
 [8.996571   7.56373413 6.25461483]]
Середнє значення =  3.871325157228288

[0.55906736 0.41780776 0.81329241 0.        ]
Сума Елементів вектора, які більше середнього значення: 
0


In [68]:
# Завдання 12 Створіть дві матриці розміром 7x7, заповніть їх випадковими цілими числами в діапазоні
# від 1 до 10 та знайдіть добуток елементів другої матриці.

mas121 = np.zeros((7,7), dtype = int )
for i in range(7):
    for j in range(7):        
        mas121[i,j] = np.random.randint(0,10)
        
mas122 = np.zeros((7,7), dtype = int )
for i in range(7):
    for j in range(7):        
        mas122[i,j] = np.random.randint(0,10)

temp = 1
mult = 1
for i in range(7):
    for j in range(7):        
        mult *= temp
        temp = mas122[i,j]
print(mas122)
print(" Добуток елементів = ")
print(mult)
print(mas122.prod())


[[2 6 8 2 3 3 7]
 [0 8 7 8 8 1 4]
 [7 8 7 2 1 5 9]
 [6 6 3 2 3 0 9]
 [9 8 2 0 5 0 7]
 [3 5 5 9 5 1 7]
 [5 2 3 0 1 5 0]]
 Добуток елементів = 
0
0


In [74]:
# Завдання 13 Створіть дві матриці розміром 7x7, заповніть їх випадковими цілими 
# числами в діапазоні від -10 до 10 та знайдіть суму їх елементів.
mas131 = np.zeros((7,7), dtype = int )

for i in range(7):
    for j in range(7):        
        mas131[i,j] = np.random.randint(-10,10)
        
mas132 = np.zeros((7,7), dtype = int )
for i in range(7):
    for j in range(7):        
        mas132[i,j] = np.random.randint(-10,10)

print(mas131)
print()
print(mas132)
print()
sum1 = mas131.sum()
sum2 = mas132.sum()
sum3 = sum1 + sum2
print(" Сума елементів матриці 1 = " + str(sum1))
print(" Сума елементів матриці 2 = " + str(sum2))
print(" Сума елементів матрицm = " + str(sum3))

[[  7   8  -7   9  -3  -5   3]
 [  6  -2   5  -3   7  -8  -5]
 [  2   5   3   9  -1   0 -10]
 [ -8   7   8   4   8   9  -4]
 [  1   7  -7   3   7  -1  -5]
 [  2   9  -3 -10  -5  -1  -1]
 [  4  -9  -5  -8   2  -7  -3]]

[[ -9   1  -8   5   3 -10  -5]
 [  1  -4   8  -2  -8 -10  -8]
 [ -4  -8   3   5  -7  -7 -10]
 [  7  -6 -10  -5 -10 -10   2]
 [ -4  -1  -4  -6   6  -9   0]
 [ -4  -1  -2  -8   6   9 -10]
 [ -5  -3   5  -4  -6  -6  -8]]

 Сума елементів матриці 1 = 14
 Сума елементів матриці 2 = -161
 Сума елементів матрицm = -147


In [77]:
# Завдання 14 Створіть матрицю розміром 10x10, заповніть її випадковими цілими числами в діапазоні 
# від 1 до 100 та знайдіть середнє арифметичне значення елементів матриці.

mas141 = np.zeros((10,10), dtype = int )

for i in range(10):
    for j in range(10):        
        mas141[i,j] = np.random.randint(1,100)
print(mas141)
print()
print(" Середнє арифметичне = " + str(mas141.mean()))

[[58 40 17 70 23 38  2 63 87 94]
 [75 80 57 54 78  2 12 99 45 94]
 [77 35 91 51 90 37 44  9 95  7]
 [55 52 26 66 65 40 37 64 26 98]
 [82 70 46 62 91 66  8 80 35 94]
 [89 61 89 98 79 89 53 77 39 55]
 [77 17 80 72  5 42 76 47 93 73]
 [84 60 19 95 30 42 90 65 34 10]
 [51 27 78 50 46 53 99 28 86 44]
 [ 3 22 50 65 55  2 11 78 91 61]]

 Середнє арифметичне = 56.27


In [87]:
# Завдання 15 Створіть матрицю розміром 8x8, заповніть її випадковими дійсними числами в діапазоні від
# -1 до 1 та знайдіть вектор-стовпчик, що містить найменший елемент у кожному рядку матриці.

mas151 = np.zeros((8,8), dtype = float )

for i in range(8):
    for j in range(8):        
        rand = np.random.uniform(-1,1)
        mas151[i,j] = round(rand, 3)
print(mas151)
print()
mas152 = np.zeros((8), dtype = float )
for i in range(8):
    mas152[i] = mas151[i].min()
print(" вектор найменших елементів: ")
print(mas152)


[[ 0.428  0.573  0.16   0.344 -0.161 -0.931  0.319  0.295]
 [ 0.033  0.694  0.229 -0.314  0.019 -0.244 -0.8   -0.103]
 [-0.211  0.657  0.186  0.404 -0.349 -0.513  0.276 -0.857]
 [ 0.227  0.961  0.926 -0.392  0.836 -0.103 -0.203 -0.689]
 [-0.943  0.213  0.241  0.291  0.84   0.855 -0.759 -0.928]
 [-0.929  0.855 -0.74   0.049  0.603  0.659  0.408  0.713]
 [-0.887  0.707 -0.604 -0.801  0.193 -0.477  0.258  0.269]
 [ 0.066  0.778  0.669  0.347 -0.792  0.538  0.501  0.594]]

 вектор найменших елементів: 
[-0.931 -0.8   -0.857 -0.689 -0.943 -0.929 -0.887 -0.792]


In [ ]:
# Отже, було проведено роботу з одновимірними та двовимірними масивами, а також функціями для роботи з ними (numpy)